$(document).ready(function (){
    $('.featured-logos__carousel').owlCarousel({
        margin:80,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    })

    $('.upcoming-university-events__carousel').owlCarousel({
        loop:true,
        margin:45,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:false
            },
            600:{
                items:2,
                nav:false
            },
            1000:{
                items:2,
                nav:false,
                loop:false
            }
        }
    })

    $('.countries-we-coverd__carousel').owlCarousel({
        loop:true,
        margin:45,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:false
            },
            600:{
                items:1,
                nav:false
            },
            1000:{
                items:3,
                nav:false,
                loop:false
            }
        }
    })

    $('.testimonial--carousel').owlCarousel({
        loop:true,
        margin:60,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:false
            },
            600:{
                items:1,
                nav:false
            },
            1000:{
                items:2,
                nav:false,
                loop:false,
                stagePadding:130,
            }
        }
    })
})